server:
  port: 8181

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:testdb
    jpa:
      hibernate:
        ddl-auto: update
  h2:
    console:
      enabled: true
app:
  topics:
    novice-players-topic: novice-players